import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "swiper/css";
import "./fonts.css";
import "./globals.css";

export const metadata = {
  title: "Churassco Restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-brown font-helvetica text-white antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
